### ISSUE TITLE
why am i getting error while using "nth-child:w-1/2" with tailwind-nth-child?

### ISSUE THREAD

**Issue by devAnkitkr** [wellssu0/tailwind-nth-child#1]
Here is the error log
"error - ./node_modules/next/dist/build/webpack/loaders/css-loader/src/index.js??ruleSet[1].rules[2].oneOf[8].use[1]!./node_modules/next/dist/build/webpack/loaders/postcss-loader/src/index.js??ruleSet[1].rules[2].oneOf[8].use[2]!./styles/globals.css
Error: Unexpected "/" found."

**Comment by Noitidart** [comment]
Were you able to figure this out?

**Comment by wellssu0** [comment]
Sorry, just noticed this issue, delayed everyone, and now it has been fixed

**Comment by Noitidart** [comment]
Thanks @wellssu0 for your amazing work!

By chance could you please let me know if my config is right, things seem to work when I do this code, but my config doesn't match the current readme in this repo. I am using Tailwind 3.0.18

Heres my config:
```
const Nth = require('tailwind-nth-child');

const every = new Nth('every', '1n+0');
const nth2n = new Nth('2n', '2n+0');
const nth3n = new Nth('3n', '3n+0');
const nth4n = new Nth('4n', '4n+0');
const nth5n = new Nth('5n', '5n+0');

module.exports = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx}',
    './components/**/*.{js,ts,jsx,tsx}'
  ],

  theme: {
    fontFamily: {
      sans: ['Lato'],
      serif: ['Rambla']
    },
  },

  plugins: [
    require('@tailwindcss/forms'),
    require('tailwindcss-dir')(),
    every.nthChild(),
    nth2n.nthChild(),
    nth3n.nthChild(),
    nth4n.nthChild(),
    nth5n.nthChild()
  ],

  variants: {
    float: ['responsive', 'direction'],
    margin: ['responsive', 'direction'],
    padding: ['responsive', 'direction']
  }
};
```

I use it like this succesfully:
```
<div className="flex flex-wrap nth-child-every:pr-2 sm:nth-child-every:pr-0 sm:nth-child-2n:pr-2">
  <!-- Card -->
  <div className="pl-2">...</div>
  <div className="pl-2">...</div>
  <div className="pl-2">...</div>
</div>
```

**Comment by wellssu0** [comment]
> 

This configuration is available, but there is no need to write variant configurations on tailwindcss 3.0, so it is also possible to omit variant configurations.

Reference: https://tailwindcss.com/blog/tailwindcss-v3#just-in-time-all-the-time

**Comment by Noitidart** [comment]
Oh! Thanks very much, I'm new to tailwind config, been just copy pasting it, don't really undersatnd it yet. This is awesome. I used this to make a `every:` that hits every child, very useful thanks!
